import type { SunState } from "./sunState";
import type { Timeline } from "./sunTimeline";

// Phase 4 export: turn a tuned session into a pasteable `sunTuning.ts`. The base look + the keyframe
// timeline are plain data, so a pretty-printed JSON body is already valid TypeScript — we just wrap it
// with typed exports and the import paths the hero integration will use. Driving `SUN_TIMELINE` with
// scrollProgress instead of a playhead is all that's left to ship it (docs/fractured-sun-lab-plan.md §5).

export function formatSunTuningSource(
  base: SunState,
  timeline: Timeline,
): string {
  const baseBody = JSON.stringify(base, null, 2);
  const timelineBody = JSON.stringify(timeline, null, 2);
  return `// Fractured sun tuning — generated by /sun-lab. Do not edit by hand; re-export from the lab.
//
// To use: import these two and drive the timeline's time from the hero's scroll progress —
//   const state = resolveState(SUN_BASE, SUN_TIMELINE, scrollProgress * SUN_TIMELINE.duration);
import type { SunState } from "@/components/lab/SunLab/sunState";
import type { Timeline } from "@/components/lab/SunLab/sunTimeline";

export const SUN_BASE: SunState = ${baseBody};

export const SUN_TIMELINE: Timeline = ${timelineBody};
`;
}
