// GENERATED by scripts/buildFleetDrawings.mjs — do not edit.
// Re-run `npm run build:drawings` after changing the fleet or the extraction constants.
//
// The points live in public/deck-drawings.bin and are fetched at runtime; only the facts a caller needs
// before the fetch lands are here. See deckDrawings.ts for the decoder.

export const DECK_DRAWINGS_URL = '/deck-drawings.bin';
export const DECK_DRAWINGS_MAGIC = 1146630486;
export const DECK_DRAWINGS_VERSION = 2;
export const DECK_DRAWINGS_HEADER_BYTES = 24;
export const DECK_DRAWINGS_COORDINATE_SCALE = 32767;
export const DECK_DRAWINGS_POINTS = 4096;
export const DECK_DRAWINGS_SEGMENTS = 5531;
/** In DECK_SERVICES order. For logs and for nothing else. */
export const DECK_DRAWING_NAMES = ['web', 'mobile', 'enterprise', 'ai'] as const;

/**
 * The one craft that becomes a ship. Every other stop is a drawing and never anything else.
 */
export const DECK_HERO_INDEX = 3;

/**
 * Deck units: a stored coordinate is (rotated - centre) / largestDimension, so the craft's
 * largest dimension spans 1. Multiply by TARGET_SIZE and lift by TARGET_SIZE * DECK_HERO_LIFT_Y
 * to land exactly where prepareVessel puts the hull.
 */
export const DECK_HERO_LIFT_Y = 0.133719;

/**
 * The shared frame every craft is expressed in — the hero's own plan view.
 *
 * DORSAL points from the craft toward the eye and NOSE is screen-up, so rotating the rig until
 * those two axes face the camera and point up reproduces the drawing exactly.
 *
 * ⚠ A DRAWING is the 3D cloud with its DORSAL component removed — one dot product, done in the
 * vertex shader, which is why no 2D array is baked. The flatten is LINEAR and therefore commutes
 * with the morph: flattening a crossing and crossing two flattened craft are the same thing.
 */
export const DECK_PLAN_DORSAL = [0.000000, -1.000000, -0.000000] as const;
export const DECK_PLAN_NOSE = [-0.000000, 0.000000, -1.000000] as const;
export const DECK_PLAN_RIGHT = [-1.000000, -0.000000, 0.000000] as const;
