// GENERATED by scripts/buildLoaderShapes.mjs — do not edit.
// Re-run `npm run build:shapes` after changing anything in /loader-shapes-src.
//
// The points themselves live in public/loader-shapes.bin and are fetched at runtime; only the facts the
// renderer needs before the fetch lands are here, so this stays a handful of bytes in the loader's
// own chunk. See loaderShapes.ts for the decoder.

export const LOADER_SHAPES_URL = '/loader-shapes.bin';
export const LOADER_SHAPE_MAGIC = 1448620360;
export const LOADER_SHAPE_VERSION = 1;
export const LOADER_SHAPE_HEADER_BYTES = 16;
export const LOADER_SHAPE_COORDINATE_SCALE = 32767;
/** The most the shader can carry — see MAX_SHAPES in the build script. */
export const LOADER_SHAPE_MAX = 4;
/** In cycle order, which is filename order. For logs and for nothing else. */
export const LOADER_SHAPE_NAMES = ['galaxy', 'solar-system', 'saturn', 'meteor'] as const;
